### ISSUE TITLE
better error messaging

### ISSUE THREAD

**Issue by lostmygithubaccount** [Azure/azureml-previews#147]
```codespace ➜ ~/workspace/azureml-examples/tutorials/using-xgboost (cody/v2 ✗) $ az ml job create --file job.yaml 
Command group 'ml job' is experimental and not covered by customer support. Please use with discretion.
ERROR: CLIInternalError: The command failed with an unexpected error. Here is the traceback:
ERROR: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-01-20T17:19:51.4610000Z and the maximum allowed lifetime for this request is 43200.\r\nTrace ID: ecbd5b8e-8478-411b-b09e-811b6c388900\r\nCorrelation ID: 75282bae-9312-4654-9f18-82f5c978f9c3\r\nTimestamp: 2021-01-22 18:03:16Z","error_codes":[70043],"timestamp":"2021-01-22 18:03:16Z","trace_id":"ecbd5b8e-8478-411b-b09e-811b6c388900","correlation_id":"75282bae-9312-4654-9f18-82f5c978f9c3","suberror":"token_expired"}
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 659, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 715, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 693, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 330, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 79, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 676, in get_raw_token
    tenant_dest, resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 1065, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 145, in acquire_token
    return self._acquire_token(token_func)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 128, in _acquire_token
    return token_func(self)
  File "/opt/az/lib/python3.6/site-packages/adal/authentication_context.py", line 143, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 347, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 127, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 199, in find
    is_resource_tenant_specific)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 177, in _refresh_entry_if_necessary
    return self._refresh_expired_entry(entry)
  File "/opt/az/lib/python3.6/site-packages/adal/cache_driver.py", line 153, in _refresh_expired_entry
    token_response = self._refresh_function(entry, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 137, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 339, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/token_request.py", line 112, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "/opt/az/lib/python3.6/site-packages/adal/oauth2_client.py", line 289, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"interaction_required","error_description":"AADSTS70043: The refresh token has expired or is invalid due to sign-in frequency checks by conditional access. The token was issued on 2021-01-20T17:19:51.4610000Z and the maximum allowed lifetime for this request is 43200.\r\nTrace ID: ecbd5b8e-8478-411b-b09e-811b6c388900\r\nCorrelation ID: 75282bae-9312-4654-9f18-82f5c978f9c3\r\nTimestamp: 2021-01-22 18:03:16Z","error_codes":[70043],"timestamp":"2021-01-22 18:03:16Z","trace_id":"ecbd5b8e-8478-411b-b09e-811b6c388900","correlation_id":"75282bae-9312-4654-9f18-82f5c978f9c3","suberror":"token_expired"}
To open an issue, please run: 'az feedback'
```

could just tell me to run `az login` again or something more friendly 

AB#1020617

**Comment by paulshealy1** [comment]
@lostmygithubaccount can you file this in the azure-cli repo? This never reaches our code.
